### ISSUE TITLE
HomeWhiz blocking all HomeAssistant

### ISSUE THREAD

**Issue by Kahless656** [home-assistant-HomeWhiz/home-assistant-HomeWhiz#208]
HomeWhiz try open 100000 connection in 5 minutes and blocking all comunication with HA ![image](https://github.com/home-assistant-HomeWhiz/home-assistant-HomeWhiz/assets/75547172/a39bb388-b47d-4500-bf9b-98d8e79f1855)

**Comment by ReX1983** [comment]
I also have the same issue. 

In my case, I couldn't find any message in the logs, so it took me weeks to identify the root cause of my HA randomly slowing down to the point of being killed and restarted by the supervisor. 

My setup is:
- Core: 2024.4.3
- Supervisor: 2024.04.0
- Operating System: 12.2
- Frontend: 20240404.2
- Beko washing machine / dryer wdik854421f
- Bluetooth connection via ESPHome BLE Proxy
- RPI4 

Thanks for your help!

**Comment by muzo178** [comment]
Same here. 

Bluetooth connection to washing machine via ESPHome BLE Proxy eventually crashes HA. I also have a dryer connected via Wifi and that runs expectedly.

**Comment by TechHummel** [comment]
Thanks for your reports. I will merge all pending changes later today and create a new release.

**Comment by TechHummel** [comment]
I released a new version, let's hope that this will fix it.

**Comment by TTLucian** [comment]
Hi. I've updated the integration to latest version but I think the issue is still present.
Home assistant is not starting and logs are filled with errors like this:
```2024-04-18 17:23:16.347 ERROR (MainThread) [homeassistant] Error doing job: Exception in callback <_asyncio.TaskStepMethWrapper object at 0x7f03c8975f00>()
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
RuntimeError: Cannot enter into task <Task pending name='Task-2417' coro=<RemoteProtocol._async_idle_disconnect() running at /usr/local/lib/python3.12/site-packages/androidtvremote2/remote.py:198>> while another task <Task cancelling name='ble-proxy-bedroom @ 192.168.1.52: aioesphomeapi connect' coro=<ReconnectLogic._connect_once_or_reschedule() running at /usr/local/lib/python3.12/site-packages/aioesphomeapi/reconnect_logic.py:298> wait_for=<Future finished result=None>> is being executed.```
The only thing using the BLE proxy is the HomeWhiz device.

**Comment by TechHummel** [comment]
@TTLucian This seems to be a different issue. I'm not even sure if this is directly related to the HomeWhiz integration.

I'll close this ticket for now. Please respond if the issue reoccurred.

**Comment by ReX1983** [comment]
> @TTLucian This seems to be a different issue. I'm not even sure if this is directly related to the HomeWhiz integration.
> 
> I'll close this ticket for now. Please respond if the issue reoccurred.

The issue has been fixed, thanks!

But a potentially related issue has appeared: now the entities go unavailable quite often. This never happened before. Could it be that the earlier implementation tried more often while with the new code, when the connection drops, it doesn't always retry?

**Comment by TechHummel** [comment]
If this is the case, we should be able to tell from the logs.
Before the last release, the integration refreshed its login token every few seconds whereas now this happens less frequently (at least for me). Maybe it's related to this change!

**Comment by ReX1983** [comment]
Please let me know if (and how) I should enable debug logging. I can't see any HomeWhiz message in the log (beside the start  up message).
